// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import PingReducer from "../ping_reducer";
import RegisterAsDisplayReducer from "../register_as_display_reducer";
import SendInputReducer from "../send_input_reducer";

export type PingParams = __Infer<typeof PingReducer>;
export type RegisterAsDisplayParams = __Infer<typeof RegisterAsDisplayReducer>;
export type SendInputParams = __Infer<typeof SendInputReducer>;

