// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  x: __t.f32(),
  y: __t.f32(),
  lastInputX: __t.f32().name("last_input_x"),
  lastInputY: __t.f32().name("last_input_y"),
  lastUpdate: __t.timestamp().name("last_update"),
  role: __t.string(),
});
