// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const PingLog = __t.object("PingLog", {
  identity: __t.identity(),
  clientSentAt: __t.timestamp(),
  serverReceivedAt: __t.timestamp(),
});
export type PingLog = __Infer<typeof PingLog>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  lastInputX: __t.f32(),
  lastInputY: __t.f32(),
  lastUpdate: __t.timestamp(),
  role: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const SignalRoom = __t.object("SignalRoom", {
  code: __t.string(),
  host: __t.identity(),
  offer: __t.string(),
  answer: __t.string(),
  createdAt: __t.timestamp(),
});
export type SignalRoom = __Infer<typeof SignalRoom>;

